### ISSUE TITLE
region=us-west-2, not us-east-1

### ISSUE THREAD

**Issue by BobSimons** [human-pangenomics/hpgp-data#1]
At  https://registry.opendata.aws/hpgp-data/
and in the hpgp-data.yaml file at
https://github.com/awslabs/open-data-registry/tree/master/datasets  
the AWS region for bucket=human-pangenomics is listed as **us-east-1**.
 
However, when I try to access the bucket via the AWS Java API or at
[](https://human-pangenomics.s3.us-east-1.amazonaws.com/)
AWS returns "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' " (or similar from the URL).

If I try [](https://human-pangenomics.s3.us-west-2.amazonaws.com/)
it succeeds.

Can you please investigate and perhaps change the yaml file so the region is listed as us-west-2?
Thank you.

**Comment by mitenjain** [comment]
Thank you for your comment. I am checking on this and will get back to you.

**Comment by mitenjain** [comment]
I have created a PR with the corrected region. Thank you for bringing this to our notice.
