### ISSUE TITLE
Multiple PacBio bams

### ISSUE THREAD

**Issue by jbelyeu** [human-pangenomics/hpgp-data#10]
Dumb question maybe but why are there multiple bams for the same data type/sample? For example HG01109 has three bams for HiFi and all are about the same age.

**Comment by skoren** [comment]
This corresponds to multiple SMRT cells (https://www.pacb.com/products-and-services/consumables/) being sequence for the same sample. Typically to get enough coverage from HiFi you need 3-4 cells. Similar to multiple flow cells on ONT.

**Comment by jbelyeu** [comment]
gotcha, many thanks!
