### ISSUE TITLE
What should I cite?

### ISSUE THREAD

**Issue by jbelyeu** [human-pangenomics/hpgp-data#11]
Sorry, one more question. I don't see direct guidance on a source to cite when using this data. Preferences?

**Comment by skoren** [comment]
For the ONT, I'd say cite the Shasta paper: https://www.nature.com/articles/s41587-020-0503-6. The HiFi data is part of the HPRC (https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0) so follow their guidance. The Illumina came from NY Genome center: https://www.internationalgenome.org/data-portal/data-collection/30x-grch38. The CLR, 10X, and parental Illumina are from NIH and there isn't a citation outside of this GitHub.

**Comment by jbelyeu** [comment]
Ah, makes sense, thanks
