### ISSUE TITLE
Metadata for FASTQs

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [human-pangenomics/hpgp-data#2]
Is there metadata available about the people whose genomes were sequenced? 
Even basic metadata such as whether they were diseased or anything like that? 

I'd imagine you can do that since you are already posting the genomic information for free to the world. 

Thanks for this project!

**Comment by mitenjain** [comment]
These are previously consented samples from 1000 Genomes Project. 

As noted in our manuscript (https://www.nature.com/articles/s41587-020-0503-6), these are "low-passage (six passages), human cell lines of the offspring of parent-child trios from the 1,000 Genomes Project and genome-in-a-bottle (GIAB) sample collections. Samples were selected to maximize captured allelic diversity".

Hope this addresses your question.

**Comment by YogiOnBioinformatics** [comment]
It does! 
Thanks for the response!
