### ISSUE TITLE
Permission errors for downloading 10X

### ISSUE THREAD

**Issue by rwdavies** [human-pangenomics/hpgp-data#3]
Hi,

I was trying to download the 10X fastq files from the Amazon repository. Most worked fine e.g. for HG01243 at  
`https://s3-us-west-2.amazonaws.com/human-pangenomics/HG01243/10X/H_IJ-HG01243-HMW-Tube_2-lib1_S2_L001_R2_001.fastq.gz`
works fine

But for HG02723 I'm getting an error. On the command line I get 
`wget https://s3-us-west-2.amazonaws.com/human-pangenomics/HG02723/10X/H_IJ-HG02723-HMW-Tube_1-lib1_S1_L003_R1_001.fastq.gz
--2020-05-27 14:59:00--  https://s3-us-west-2.amazonaws.com/human-pangenomics/HG02723/10X/H_IJ-HG02723-HMW-Tube_1-lib1_S1_L003_R1_001.fastq.gz
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.217.80
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.217.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-05-27 14:59:01 ERROR 403: Forbidden.
`
and in my web browser I get an XML blurb that includes "AccessDenied" 
`https://s3-us-west-2.amazonaws.com/human-pangenomics/HG02723/10X/H_IJ-HG02723-HMW-Tube_1-lib1_S1_L003_R1_001.fastq.gz`

Thanks,
Robbie

**Comment by mitenjain** [comment]
Hello,

Sorry for the hassle. It appears that both 10X and BNG data have the same issue here. Let me check with the institutions that submitted those data, and fix permissions. I'll ping you back when done. 

Thank you. 
Miten

**Comment by mitenjain** [comment]
It should be fixed now. Thank you for bringing this up.
