### ISSUE TITLE
HG002, HG005, and HG00733 data

### ISSUE THREAD

**Issue by vahidAK** [human-pangenomics/hpgp-data#7]
Hi,

In the first version of the ReadMe file, you also provided the link to HG002, HG005, and HG00733 raw nanopore and base called reads. However, those links are not available anymore.
https://s3-us-west-2.amazonaws.com/human-pangenomics/HG002/nanopore/
https://s3-us-west-2.amazonaws.com/human-pangenomics/HG005/nanopore/
https://s3-us-west-2.amazonaws.com/human-pangenomics/HG00733/nanopore/

I was wondering where those files can be accessed. I have used them in my recent work.

Many thanks,
Vahid

**Comment by skoren** [comment]
HG002 has it's own GitHub repo here: https://github.com/human-pangenomics/HG002_Data_Freeze_v1.0. The rest you can navigate through the S3 links from the year1 freeze: https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0

**Comment by mitenjain** [comment]
Thank you @skoren. @vahidAK, let us know if you need any further information.

**Comment by vahidAK** [comment]
Thanks a lot
