### ISSUE TITLE
Diversity panel DNA source

### ISSUE THREAD

**Issue by qin218** [human-pangenomics/hpgp-data#8]
May I ask for T2T diversity panel, what is the DNA source? Are all of them from blood? Thanks.

**Comment by qin218** [comment]
And what is the DNA extraction protocol and Nanopore sequencing protocol (which kit was used, is it PCR-free, etc)? Thanks.

**Comment by skoren** [comment]
The source is cell lines from https://www.coriell.org. I believe they are all B-Lymphocyte transformed with EBV but you can check specific samples at Coriell to confirm. The Nanopore sequencing is PCR-free and comes from UCSC. There's more info on all the data types on the HPRC YR1 data freeze page: https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0

**Comment by qin218** [comment]
Thanks so much for your reply.
