### ISSUE TITLE
Download of fasta and gtf of HG01243.v3.0

### ISSUE THREAD

**Issue by tsimoneaux** [human-pangenomics/hpgp-data#9]
https://www.ncbi.nlm.nih.gov/assembly/GCA_018873775.2
ftp://ftp.ccb.jhu.edu/pub/data/Homo_sapiens/PR1/v3.0/Annotation/pr1v3.0_final.gff3

I am unable to access the fasta file or the gtf file for this genome. On the ncbi website there are 0 bytes in when attempting to use either Source database (GenBank or RefSeq). I am using a dell laptop. Can  you please help me with downloading these files?

email: tsimoneaux@msm.edu

**Comment by skoren** [comment]
This is an unrelated project to use the data we released here. I'd contact the authors of this manuscript: https://www.biorxiv.org/content/10.1101/2021.06.10.447952v3. That said, when I go to NCBI and select download assembly and pick GenBank I get a 1gb gzipped file and I'm also able to get the gff3 using curl as well.
